In [1]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv('data//classification.csv')
df

           age   interest  success
0    23.657801  18.859917      0.0
1    22.573729  17.969223      0.0
2    32.553424  29.463651      0.0
3     6.718035  25.704665      1.0
4    14.401919  16.770856      0.0
..         ...        ...      ...
292  27.697220  18.799309      0.0
293  15.150959  72.000352      1.0
294  22.264378  68.453459      1.0
295  25.677420  90.118212      1.0
296  21.215594  48.265520      1.0

[297 rows x 3 columns]

In [3]:
X = df[['age', 'interest']]
y = df['success']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [5]:
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

In [6]:
y_pred = clf.predict_proba(X_test)

In [15]:
y_pred

array([[5.73064891e-06, 9.99994269e-01],
       [4.62433041e-01, 5.37566959e-01],
       [2.08523969e-06, 9.99997915e-01],
       [1.09822264e-04, 9.99890178e-01],
       [1.08799803e-02, 9.89120020e-01],
       [4.95965766e-01, 5.04034234e-01],
       [2.29976714e-02, 9.77002329e-01],
       [9.59760648e-01, 4.02393519e-02],
       [4.85782126e-03, 9.95142179e-01],
       [9.05522991e-01, 9.44770086e-02],
       [8.01299546e-01, 1.98700454e-01],
       [1.68358450e-06, 9.99998316e-01],
       [6.91423742e-02, 9.30857626e-01],
       [5.56313683e-03, 9.94436863e-01],
       [1.38001523e-04, 9.99861998e-01],
       [9.45253101e-01, 5.47468994e-02],
       [9.56512559e-01, 4.34874406e-02],
       [4.25730016e-03, 9.95742700e-01],
       [1.20389021e-03, 9.98796110e-01],
       [9.72468319e-01, 2.75316808e-02],
       [3.14157719e-01, 6.85842281e-01],
       [7.61106443e-01, 2.38893557e-01],
       [7.67607305e-02, 9.23239270e-01],
       [6.35198636e-01, 3.64801364e-01],
       [2.15997970e-01, 7.84002030e-01],
       [6.08653284e-01, 3.91346716e-01],
       [9.75205946e-01, 2.47940538e-02],
       [3.04033022e-03, 9.96959670e-01],
       [8.91690895e-01, 1.08309105e-01],
       [9.53089951e-01, 4.69100492e-02],
       [9.39999706e-01, 6.00002944e-02],
       [8.75884315e-05, 9.99912412e-01],
       [3.79818316e-03, 9.96201817e-01],
       [1.79833088e-02, 9.82016691e-01],
       [4.73705681e-04, 9.99526294e-01],
       [1.18506837e-01, 8.81493163e-01],
       [9.58011055e-01, 4.19889449e-02],
       [9.40622396e-01, 5.93776039e-02],
       [9.73224476e-01, 2.67755237e-02],
       [9.55212838e-01, 4.47871616e-02],
       [9.65895108e-01, 3.41048921e-02],
       [9.76480310e-01, 2.35196902e-02],
       [1.42799344e-02, 9.85720066e-01],
       [2.21823228e-04, 9.99778177e-01],
       [2.23281201e-04, 9.99776719e-01],
       [5.63587193e-01, 4.36412807e-01],
       [8.70845949e-01, 1.29154051e-01],
       [5.40360646e-04, 9.99459639e-01],
       [2.87469067e-04, 9.99712531e-01],
       [7.80250611e-01, 2.19749389e-01],
       [8.47647706e-01, 1.52352294e-01],
       [1.16689005e-01, 8.83310995e-01],
       [1.76592952e-05, 9.99982341e-01],
       [8.09118407e-01, 1.90881593e-01],
       [9.34528167e-01, 6.54718330e-02],
       [3.85156712e-03, 9.96148433e-01],
       [8.46738277e-01, 1.53261723e-01],
       [8.54598200e-01, 1.45401800e-01],
       [8.53632939e-01, 1.46367061e-01],
       [1.89825013e-04, 9.99810175e-01],
       [6.96483060e-01, 3.03516940e-01],
       [8.21596720e-01, 1.78403280e-01],
       [7.72471835e-03, 9.92275282e-01],
       [7.85035978e-01, 2.14964022e-01],
       [1.95506675e-01, 8.04493325e-01],
       [8.36329920e-01, 1.63670080e-01],
       [9.43332961e-01, 5.66670387e-02],
       [3.28149407e-07, 9.99999672e-01],
       [9.65881545e-01, 3.41184549e-02],
       [8.03687268e-02, 9.19631273e-01],
       [1.27089001e-05, 9.99987291e-01],
       [1.31396053e-03, 9.98686039e-01],
       [9.59928129e-01, 4.00718707e-02],
       [9.63871496e-01, 3.61285041e-02],
       [4.39274915e-03, 9.95607251e-01],
       [2.70469869e-03, 9.97295301e-01],
       [3.81942831e-01, 6.18057169e-01],
       [2.18712004e-04, 9.99781288e-01],
       [6.26629558e-01, 3.73370442e-01],
       [6.74993769e-01, 3.25006231e-01],
       [8.13101917e-01, 1.86898083e-01],
       [3.42332689e-05, 9.99965767e-01],
       [7.11558312e-03, 9.92884417e-01],
       [9.48111972e-01, 5.18880277e-02],
       [5.14620963e-01, 4.85379037e-01],
       [3.84626502e-04, 9.99615373e-01],
       [1.39025632e-04, 9.99860974e-01],
       [8.86701899e-01, 1.13298101e-01],
       [7.23468725e-01, 2.76531275e-01],
       [9.18214137e-01, 8.17858627e-02]])

In [8]:
X_test

           age   interest
158  14.722866  83.226240
49   12.571706  43.638702
128  39.085745  82.355800
143  26.271454  74.781376
54   26.359220  60.521433
..         ...        ...
293  15.150959  72.000352
68   13.253034  74.838306
285  27.727928  27.688066
123  13.972922  37.718690
272  30.011627  22.847910

[90 rows x 2 columns]

In [17]:
added_prob = pd.DataFrame(y_pred, columns=['y_proba_0', 'y_proba_1'], index=y_test.index)

In [18]:
added_prob

     y_proba_0  y_proba_1
158   0.000006   0.999994
49    0.462433   0.537567
128   0.000002   0.999998
143   0.000110   0.999890
54    0.010880   0.989120
..         ...        ...
293   0.000385   0.999615
68    0.000139   0.999861
285   0.886702   0.113298
123   0.723469   0.276531
272   0.918214   0.081786

[90 rows x 2 columns]

In [22]:
full_df = pd.concat([X_test, added_prob, y_test], axis=1, reset_index)

SyntaxError: positional argument follows keyword argument (3928008369.py, line 1)

In [21]:
full_df.reset_index(drop=True)

          age   interest  y_proba_0  y_proba_1
0   14.722866  83.226240   0.000006   0.999994
1   12.571706  43.638702   0.462433   0.537567
2   39.085745  82.355800   0.000002   0.999998
3   26.271454  74.781376   0.000110   0.999890
4   26.359220  60.521433   0.010880   0.989120
..        ...        ...        ...        ...
85  15.150959  72.000352   0.000385   0.999615
86  13.253034  74.838306   0.000139   0.999861
87  27.727928  27.688066   0.886702   0.113298
88  13.972922  37.718690   0.723469   0.276531
89  30.011627  22.847910   0.918214   0.081786

[90 rows x 4 columns]